### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Aericio** [SalmonCraftPE/StatsPE#1]
## General:

- [ ] JSON Support (probably YAML and not json)

- [ ] MySQL Support (Stats showing on Website)

- [ ] Create an updater

## What the plugin should save:

- [ ] Playername

- [ ] ClientID

- [ ] LastIP

- [ ] FirstJoin

- [ ] LastJoin

- [ ] Joincount

- [ ] Killcount

- [ ] Deathcount

- [ ] Kickcount

- [ ] Onlinetime

- [ ] BlocksBreaked

- [ ] BlocksPlaced

- [ ] ChatMessages

- [ ] Fishcatchcount

- [ ] Bedcount (When player enters a bed)

- [ ] Eatcount

- [ ] Craftcount

## Additional:

- [ ] "/stats [Player]" command

- [ ] GuessTheNumber stats

- [ ] Don't show CID / IP for normal users.
